version: '3.9'
services:
  rp2040_rust_app:
    build: .
    image: "rp2040_rust_app:0.0.1"
    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - ../:/home/rp2040/rp2040_rust_app:cached
    # isolation: process
    # devices:
    #   - "class/{86E0D1E0-8089-11D0-9CE4-08003E301F73}"
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
